title: Maciek's blog
description: >- 
  The place on the Internet where I share my notes. Sharing is caring, right?
url: "https://mjarosie.github.io" 
twitter_username: mjarosie
github_username: mjarosie
stackoverflow_username: mjarosie
stackoverflow_user_id: "3088888"
linkedin_username: maciej-jarosiewicz

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

header_pages:
  - about.md
  - categories.md
  - tags.md

minima:
  date_format: "%e %B, %Y"

disqus:
  shortname: mjarosie-blog

clicky_analytics: 101221712